openapi: "3.0.0"
info:
  title: User profile updation
  version: "1.0"
paths:
  /api/customer/update:
    put:
      summary: Update user profile
      description: Updates the users profile details.
      requestBody:
        description: The updated user profile with latest details.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Profile udpated successfully
        "400":
          description: Invalid request. The request body is missing or malformed.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Shipment not found. The specified shipmentId does not exist.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
        type: object
        properties:
          code:
            type: integer
          message:
            type: string
        example:
          code: 400
          message: "Profile not updated"
    User:
      type: object
      properties:
        name:
          type: string
          description: name of User
          example: user's name
        email:
          type: string
          description: email of user
          example: user@name.com
        address:
          type: string
          description: address of user
          example: 123 test road
        password:
          type: string
          description: password of user
          example: uYbudisdjbnasi
        userType:
          type: string
          description: type of user
          example: CUSTOMER
